config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#                      root GET    /                                                                                        pages#home
#              like_article GET    /articles/:id/like(.:format)                                                             articles#like
#            unlike_article GET    /articles/:id/unlike(.:format)                                                           articles#unlike
#              articles_add GET    /articles/add(.:format)                                                                  articles#add
#                           DELETE /users/:id(.:format)                                                                     users#destroy
#               collections GET    /collections(.:format)                                                                   collections#show
#                     pages GET    /pages(.:format)                                                                         pages#index
#                           POST   /pages(.:format)                                                                         pages#create
#                  new_page GET    /pages/new(.:format)                                                                     pages#new
#                 edit_page GET    /pages/:id/edit(.:format)                                                                pages#edit
#                      page GET    /pages/:id(.:format)                                                                     pages#show
#                           PATCH  /pages/:id(.:format)                                                                     pages#update
#                           PUT    /pages/:id(.:format)                                                                     pages#update
#                           DELETE /pages/:id(.:format)                                                                     pages#destroy
#                  articles GET    /articles(.:format)                                                                      articles#index
#                           POST   /articles(.:format)                                                                      articles#create
#               new_article GET    /articles/new(.:format)                                                                  articles#new
#              edit_article GET    /articles/:id/edit(.:format)                                                             articles#edit
#                   article GET    /articles/:id(.:format)                                                                  articles#show
#                           PATCH  /articles/:id(.:format)                                                                  articles#update
#                           PUT    /articles/:id(.:format)                                                                  articles#update
#                           DELETE /articles/:id(.:format)                                                                  articles#destroy
#                           GET    /collections(.:format)                                                                   collections#index
#                           POST   /collections(.:format)                                                                   collections#create
#            new_collection GET    /collections/new(.:format)                                                               collections#new
#           edit_collection GET    /collections/:id/edit(.:format)                                                          collections#edit
#                collection GET    /collections/:id(.:format)                                                               collections#show
#                           PATCH  /collections/:id(.:format)                                                               collections#update
#                           PUT    /collections/:id(.:format)                                                               collections#update
#                           DELETE /collections/:id(.:format)                                                               collections#destroy
#                     users GET    /users(.:format)                                                                         users#index
#                           POST   /users(.:format)                                                                         users#create
#                  new_user GET    /users/new(.:format)                                                                     users#new
#                 edit_user GET    /users/:id/edit(.:format)                                                                users#edit
#                      user GET    /users/:id(.:format)                                                                     users#show
#                           PATCH  /users/:id(.:format)                                                                     users#update
#                           PUT    /users/:id(.:format)                                                                     users#update
#                           DELETE /users/:id(.:format)                                                                     users#destroy
#             session_index GET    /session(.:format)                                                                       session#index
#                           POST   /session(.:format)                                                                       session#create
#               new_session GET    /session/new(.:format)                                                                   session#new
#              edit_session GET    /session/:id/edit(.:format)                                                              session#edit
#                   session GET    /session/:id(.:format)                                                                   session#show
#                           PATCH  /session/:id(.:format)                                                                   session#update
#                           PUT    /session/:id(.:format)                                                                   session#update
#                           DELETE /session/:id(.:format)                                                                   session#destroy
#                 users_new GET    /users/new(.:format)                                                                     users#new
#                     login GET    /login(.:format)                                                                         session#new
#                           POST   /login(.:format)                                                                         session#create
#                           DELETE /login(.:format)                                                                         session#destroy
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  root :to => 'pages#home'

  get "articles/:id/like" => "articles#like", as: :like_article
  get "articles/:id/unlike" => "articles#unlike", as: :unlike_article
  get 'articles/add' => 'articles#add'
  delete '/users/:id(.:format)' => 'users#destroy'
  get 'collections' => "collections#show"
  resources :pages
  resources :articles
  resources :collections
  resources :users
  resources :session
  get 'users/new' => 'users#new'
  get '/login' => 'session#new' # login form
  post '/login' => 'session#create' # perform a login
  delete '/login' => 'session#destroy' # perform a log out
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_svg.html.erb
<img src="">
<svg id="lumiere-all"
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   version="1.1"
   id="Layer_1"
   x="0px"
   y="0px"
   viewBox="0 0 950.90137 163.03711"
   xml:space="preserve"
   sodipodi:docname="Lumière.svg"
   width="826.90137"
   height="163.03711"
   inkscape:version="0.92.3 (unknown)"><metadata
   id="metadata92"><rdf:RDF><cc:Work
       rdf:about=""><dc:format>image/svg+xml</dc:format><dc:type
         rdf:resource="http://purl.org/dc/dcmitype/StillImage" /><dc:title></dc:title></cc:Work></rdf:RDF></metadata><defs
   id="defs90" /><sodipodi:namedview
   pagecolor="#ffffff"
   bordercolor="#666666"
   borderopacity="1"
   objecttolerance="10"
   gridtolerance="10"
   guidetolerance="10"
   inkscape:pageopacity="0"
   inkscape:pageshadow="2"
   inkscape:window-width="1920"
   inkscape:window-height="1025"
   id="namedview88"
   showgrid="true"
   inkscape:snap-grids="true"
   fit-margin-top="0"
   fit-margin-left="0"
   fit-margin-right="0"
   fit-margin-bottom="0"
   inkscape:zoom="0.76111111"
   inkscape:cx="413.45068"
   inkscape:cy="81.518556"
   inkscape:window-x="0"
   inkscape:window-y="27"
   inkscape:window-maximized="1"
   inkscape:current-layer="Layer_1"><inkscape:grid
     type="xygrid"
     id="grid94"
     originx="-546.54932"
     originy="-458.48145" /></sodipodi:namedview>
<g
   id="g85"
   transform="translate(-385.78516,-411.01758)">
  <path
   d="M 404.15527,568.77344 V 425.02539 h -18.37011 v -2.75586 h 52.58496 v 2.75586 H 420 v 143.74805 h 71.64404 v -33.0669 h 2.98535 V 571.5293 H 385.78516 v -2.75586 z"
   id="path71"
   inkscape:connector-curvature="0" />
  <path
   d="m 599.57324,553.15918 c -4.59228,13.93066 -15.30859,20.89551 -32.14795,20.89551 -15.00244,0 -25.37402,-3.17578 -31.11474,-9.5293 -5.74073,-6.35351 -8.61133,-15.95898 -8.61133,-28.81885 v -65.44433 h -13.77783 v -2.75537 h 29.16308 v 71.87402 c 0,9.79785 1.91358,17.49023 5.74073,23.07812 3.82714,5.58692 10.79248,8.38086 20.89648,8.38086 9.33838,0 16.64795,-2.9082 21.92969,-8.72558 5.28125,-5.81739 7.92187,-14.38965 7.92187,-25.71875 v -66.1333 h -13.77783 v -2.75537 h 29.16309 v 101.2666 h 14.00732 v 2.75586 h -29.39258 z"
   id="path73"
   inkscape:connector-curvature="0" />
  <path
   d="m 802.79687,568.77344 v -69.34815 c 0,-9.79785 -1.91357,-17.45215 -5.74072,-22.96289 -3.82715,-5.51123 -10.79248,-8.26709 -20.89648,-8.26709 -9.33789,0 -16.64795,2.94727 -21.9292,8.84082 -5.28174,5.89405 -7.92236,14.42871 -7.92236,25.60401 v 66.1333 h 13.77783 v 2.75586 h -43.17041 v -2.75586 h 14.00732 v -69.11865 c 0,-9.79737 -1.95166,-17.49024 -5.85547,-23.07764 -3.90381,-5.58789 -10.83105,-8.38184 -20.78174,-8.38184 -9.33789,0 -16.68603,2.90869 -22.04443,8.72608 -5.35791,5.81738 -8.03662,14.39013 -8.03662,25.71875 v 66.1333 h 14.00732 v 2.75586 H 645.0415 v -2.75586 h 14.00733 V 470.26221 H 645.0415 v -2.75537 h 29.16309 v 18.37011 c 4.7456,-13.93066 15.53809,-20.89599 32.37744,-20.89599 11.94092,0 20.93457,2.0664 26.98145,6.1997 6.04687,4.1333 9.91259,10.48633 11.59619,19.05909 3.67431,-16.83936 14.77295,-25.25879 33.29638,-25.25879 15.00245,0 25.37403,3.17627 31.11475,9.52929 5.74072,6.35303 8.61133,15.95948 8.61133,28.81836 v 65.44483 h 13.77783 v 2.75586 h -43.17041 v -2.75586 z"
   id="path75"
   inkscape:connector-curvature="0" />
  <path
   d="m 860.89648,568.77344 v -98.51123 h -14.00732 v -2.75537 h 29.16309 v 101.2666 h 14.00732 v 2.75586 h -43.17041 v -2.75586 z m -1.0332,-131.2334 c -1.91357,-2.0669 -2.8706,-4.63086 -2.8706,-7.69287 0,-3.06153 0.95703,-5.62549 2.8706,-7.69238 1.91358,-2.06641 4.5542,-3.1001 7.92188,-3.1001 3.36816,0 6.00879,1.03369 7.92236,3.1001 1.91357,2.06689 2.87061,4.63085 2.87061,7.69238 0,3.06201 -0.95704,5.62597 -2.87061,7.69287 -1.91357,2.06641 -4.5542,3.1001 -7.92236,3.1001 -3.36768,0 -6.0083,-1.03369 -7.92188,-3.1001 z"
   id="path77"
   inkscape:connector-curvature="0" />
  <path
   d="m 923.35449,560.3916 c -9.33789,-9.1084 -14.00732,-22.69482 -14.00732,-40.75928 0,-18.06396 4.47803,-31.68847 13.43359,-40.87402 8.95557,-9.18506 20.24561,-13.77734 33.87012,-13.77734 14.23682,0 25.45068,3.75049 33.64014,11.25146 8.19043,7.50147 12.28518,19.28906 12.28518,35.36328 l -0.2295,5.51075 h -76.23635 v 5.05224 c 0,17.29834 2.94678,29.81397 8.84082,37.54444 5.89356,7.73046 14.50488,11.59667 25.83301,11.59667 10.41016,0 18.71484,-1.99023 24.91504,-5.9707 6.19922,-3.98047 10.06543,-8.80273 11.5957,-14.4668 h 2.75588 c -1.68361,6.58301 -5.93264,12.09375 -12.74416,16.53321 -6.8125,4.43945 -16.03613,6.65918 -27.67041,6.65918 -14.84961,0 -26.94336,-4.55371 -36.28174,-13.66309 z m 62.45899,-51.09228 c 0,-15.46192 -2.37305,-26.2544 -7.11817,-32.37793 -4.74609,-6.12354 -12.09375,-9.18506 -22.04443,-9.18506 -9.49121,0 -16.9541,3.40625 -22.38867,10.21826 -5.43457,6.8125 -8.15186,17.26074 -8.15186,31.34473 v 5.05175 h 59.70313 z m -53.04395,-81.74805 c -4.28662,-3.36816 -6.42969,-6.50635 -6.42969,-9.41504 0,-1.99023 0.72705,-3.67383 2.18164,-5.05176 1.45411,-1.37793 3.25293,-2.06689 5.396,-2.06689 3.36816,0 6.35303,2.21972 8.95557,6.65967 l 18.59961,29.39257 h -2.75489 z"
   id="path79"
   inkscape:connector-curvature="0" />
  <path
   d="m 1034.7256,568.77344 v -65.67432 c 0,-11.63428 3.3682,-20.896 10.1035,-27.78516 6.7354,-6.88867 15.6152,-10.333 26.6367,-10.333 15.003,0 24.9531,6.50586 29.8526,19.51806 h -2.7559 c -4.2861,-11.17529 -13.0889,-16.76269 -26.4072,-16.76269 -7.961,0 -13.625,2.79394 -16.9932,8.38135 -3.3672,5.58789 -5.0517,14.19873 -5.0517,25.83349 v 66.82227 h 16.9931 v 2.75586 h -46.1562 v -2.75586 z"
   id="path81"
   inkscape:connector-curvature="0" />
  <path
   d="m 1133.4639,560.3916 c -9.3379,-9.1084 -14.0069,-22.69482 -14.0069,-40.75928 0,-18.06396 4.4776,-31.68847 13.4336,-40.87402 8.9551,-9.18506 20.2451,-13.77734 33.8701,-13.77734 14.2373,0 25.4502,3.75049 33.6407,11.25146 8.1904,7.50147 12.2851,19.28906 12.2851,35.36328 l -0.2295,5.51075 h -76.2373 v 5.05224 c 0,17.29834 2.9473,29.81397 8.8408,37.54444 5.8936,7.73046 14.5049,11.59667 25.8331,11.59667 10.4101,0 18.7148,-1.99023 24.915,-5.9707 6.2002,-3.98047 10.0654,-8.80273 11.5967,-14.4668 h 2.7549 c -1.6836,6.58301 -5.9317,12.09375 -12.7442,16.53321 -6.8125,4.43945 -16.0361,6.65918 -27.6699,6.65918 -14.8496,0 -26.9434,-4.55371 -36.2822,-13.66309 z m 62.4599,-51.09228 c 0,-15.46192 -2.373,-26.2544 -7.1191,-32.37793 -4.7451,-6.12354 -12.0938,-9.18506 -22.044,-9.18506 -9.4912,0 -16.9541,3.40625 -22.3886,10.21826 -5.4346,6.8125 -8.1524,17.26074 -8.1524,31.34473 v 5.05175 h 59.7041 z"
   id="path83"
   inkscape:connector-curvature="0" />
</g>
</svg>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>lumière</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,200,300,400,500|Source+Sans+Pro:200,300,400,600" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Oswald:200,300,400,500" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

    <% # Required for google_sign_in to add the Google JS assets and meta tags! %>
    <%= yield :head %>
  </head>

  <header class="nav-down">
    <% if @current_user.present? %>
    <%= link_to 'Home', '/articles/new' %>
    <!-- <%= link_to 'New Articles', '/articles/new' %> -->
    <%= link_to 'All Articles', articles_path %>
    <%= link_to 'Add Article', articles_add_path %>
    <%= link_to 'My Collection', collections_path %>
    <%= link_to "Sign out", login_path, :method => 'delete' %>
    <% else %>
      <%= link_to 'Sign up', new_user_path %>
      <%= link_to 'Sign in', login_path %>
    <% end %>
</header>



  <body>

          <!-- <%= render :partial => "layouts/svg" unless @current_user.present?  %> -->
          <% if @current_user.present?  %>
          <%= render :partial => "layouts/svg" %>
          <% end  %>


    <%= yield %>
  </body>
</html>